services:
  - type: web
    name: fastapi-todo-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: JWT_SECRET
        value: FlUtDByt4chxs8Px4lke5u1prqJNDUp